### ISSUE TITLE
npm install failing

### ISSUE THREAD

**Issue by ais-one** [adonisjs/adonis-rally#1]
Currently runnin ubuntu 14.04 LTS,

node 6.9.1
npm 4.0.2

The npm install will fail for version 3.10.8, it is an npm problem Please see the following link for more details [https://github.com/npm/npm/issues/14089](https://github.com/npm/npm/issues/14089).

However, even after upgrading, the next error is... 

> 34660 verbose stack TypeError: Cannot read property 'deep-extend' of undefined
34660 verbose stack     at /usr/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:35:40
34660 verbose stack     at Array.filter (native)
34660 verbose stack     at inflateShrinkwrap (/usr/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:34:49)
34660 verbose stack     at /usr/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:55:16
34660 verbose stack     at /usr/lib/node_modules/npm/node_modules/iferr/index.js:13:50
34660 verbose stack     at zalgoSafe (/usr/lib/node_modules/npm/node_modules/dezalgo/dezalgo.js:20:10)
34660 verbose stack     at finalize (/usr/lib/node_modules/npm/node_modules/realize-package-specifier/index.js:39:5)
34660 verbose stack     at /usr/lib/node_modules/npm/node_modules/realize-package-specifier/index.js:22:20
34660 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:276:29
34660 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
34661 verbose cwd /var/www/html/_adonis/adonis-rally
34662 error Linux 3.13.0-83-generic
34663 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
34664 error node v6.9.1
34665 error npm  v4.0.2
34666 error Cannot read property 'deep-extend' of undefined
34667 error If you need help, you may report this error at:
34667 error     <https://github.com/npm/npm/issues>
34668 verbose exit [ 1, true ]

No node_modules folder was created also...

**Comment by RomainLanz** [comment]
Hey @ais-one !

Remove `npm-shrinkwrap.json` file and try again.

**Comment by ais-one** [comment]
@RomainLanz yes, it works, should have tried that, thanks!
