### ISSUE TITLE
Couldn't find frontend repo

### ISSUE THREAD

**Issue by vabatta** [adonisjs/adonis-rally#16]
Adonis rally is a forum created using VueJs and AdonisJs. The API of the framework is written is Adonis and checkout the rally-frontend repo to grab the VueJs code.

Where is the cited repo?

**Comment by chrisdeuda** [comment]
Same here I couldn't find the rally-frontend Repo.

**Comment by joernroeder** [comment]
same here

**Comment by chrisferry** [comment]
ditto

**Comment by RomainLanz** [comment]
Hey all! 👋 

The frontend repo doesn't exist. This is why you cannot find it. 😄 
This repo will probably be archived in the near future, closing this for now.
