### ISSUE TITLE
Unsuccessful Cloning the Repo

### ISSUE THREAD

**Issue by renztoygwapo** [adonisjs/adonis-rally#2]
Hello, thanks for this adonis opensource project, I want to clone the repo adonis-rally, 
I have node and npm installed both are v4 up, I can clone the repo then I go to the directory
Then run the "make install" command after that I encountered an error/bugs

Can you help me this one ?

I saw this errors : 

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.7
npm ERR! npm  v4.0.2

npm ERR! Cannot read property 'deep-extend' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.7
npm ERR! npm  v4.0.2

npm ERR! Cannot read property 'extsprintf' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Cathy/Documents/jspractice/adonis/adonis-rally/npm-debug.log
make: *** [_npmi] Error 1

**Comment by thetutlage** [comment]
Seems to like some issue with `npm install`. Would you mind deleting the **node_modules** and redo `npm install`
