### ISSUE TITLE
Error when run migration.

### ISSUE THREAD

**Issue by rinodung** [adonisjs/adonis-rally#27]
I follow step 3: ```Run all migrations. node --harmony_proxies ace migration:refresh``` but get this error
MySQL Server like this:
![untitled](https://user-images.githubusercontent.com/7805715/34384307-fc25b8f8-eb4d-11e7-969e-35e225864e65.png)

**Comment by rinodung** [comment]
Problem is increment method generate int 10, and integer method generate int 11, can not map to foreign key. 

Solved: add .unsigned() after question_id, user_id....
```table.integer('question_id').unsigned().references('id').inTable('questions')
      table.integer('user_id').unsigned().references('id').inTable('users')
```

**Comment by ri8ika** [comment]
Didn't help me even using unsigned.

**Comment by ri8ika** [comment]
Hi!

I have created a PR for this. Which is fixed such error.

Thanks,
Bhojendra

**Comment by RomainLanz** [comment]
Closing since PR merged.
