### ISSUE TITLE
DB Migration Error

### ISSUE THREAD

**Issue by renztoygwapo** [adonisjs/adonis-rally#3]
Got this error when running "Make Install"
![screen shot 2016-12-22 at 10 49 00 am](https://cloud.githubusercontent.com/assets/4898681/21413736/82ed010e-c834-11e6-8c67-108c898940a1.png)

How could it fix the issue.

Thanks

**Comment by mbouclas** [comment]
The way i see it, there is a logic error in the migrations. For example, in `1468648462352_Question` the line
`table.integer('channel_id').references('id').inTable('channels')` is creating the field channel_id and tries to create a relationship to table channels which does not exist yet. So, this should like `table.integer('channel_id').unsigned().notNullable()` and then, in another migration file after all the tables are created, you need to add the relationships like so : 
```
class FixQuestionsTableTableSchema extends Schema {

  up () {
    this.table('questions', (table) => {
        table.foreign('user_id').references('id').inTable('users')
        table.foreign('channel_id').references('id').inTable('channels')
    })
  }

}
```

All we're doing is adding the relationships after all the tables are present. This worked in my case, note that you need to add a second file for answers
