### ISSUE TITLE
<App/Model>.isNew() 

### ISSUE THREAD

**Issue by lmj0011** [adonisjs/adonis-rally#7]
https://github.com/adonisjs/adonis-rally/blob/develop/app/Repositories/User.js#L42

I've been seeing this called a lot. Is it being being extending from Lucid? If so where is it in the docs?
http://adonisjs.com/docs/3.2/lucid

**Comment by RomainLanz** [comment]
Hey @lmj0011 !

This method is defined here : https://github.com/adonisjs/adonis-lucid/blob/develop/src/Lucid/Model/index.js#L793

I'll add it to the doc!
